!!python/unicode 'oryza_sativa':
  ensembl-release-38: [IRGSP-1.0, /pub/plants/release-38/fasta/oryza_sativa/dna/Oryza_sativa.IRGSP-1.0.dna.toplevel.fa.gz,
    /pub/plants/release-38/gtf/oryza_sativa/Oryza_sativa.IRGSP-1.0.38.gtf.gz]
